dropdown/dropdown/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dropdown.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^dropdown/$', 'dropdown.views.dropdown', name='dropdown'),
    url(r'^state_ajax/$', 'dropdown.views.state_ajax', name='state_ajax'),
)

dropdown/dropdown/models.py
from django.db import models

class Country(models.Model):
    name = models.CharField(max_length=30)
    
    def __str__(self):
        return self.name


class State(models.Model):
    name = models.CharField(max_length=30)
    country = models.ForeignKey(Country)

    def __str__(self):
        return self.name  

class City(models.Model):
    name = models.CharField(max_length=30)
    state = models.ForeignKey(State)

    def __str__(self):
        return self.name

dropdown/dropdown/forms.py
from django import forms
from dropdown.models import Country, State, City

class DropDownForm(forms.Form):
    country = forms.ModelChoiceField(queryset=Country.objects.all())
    state = forms.ModelChoiceField(queryset=State.objects.all())
    city = forms.ModelChoiceField(queryset=City.objects.all())

  
   
    

dropdown/dropdown/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from dropdown.forms import DropDownForm
from dropdown.models import Country, State, City
import json


def dropdown(request):
    form = DropDownForm()
    return render(request, "dropdown.html", {'form':form})

    """ 'Without using ModelForm'

    country = Country.objects.all()
    state = State.objects.all()
    city = City.objects.none()
    return render(request, "dropdown.html", {'country': country, 'state':state, 'city':city})
 
    """


def state_ajax(request):
    if request.POST and request.is_ajax():
        print "ajax"
        c_id = request.POST.get('country_id')
        state = State.objects.filter(country=c_id)

        for s in state:
            city = s.city_set.all()
            print "city", city


        state_dict = {}
        for s in state:
            state_dict[s.id] = s.name
        
        city_dict = {}
        print city
        for c in city:
            city_dict[c.id] = c.name


        data = json.dumps({
                'state_dict': state_dict,
                'city_dict': city_dict,
            })

        print data
        return HttpResponse(data, content_type="application/json")

dropdown/templates/base.html
{% load staticfiles %}
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
      <link href="{% static "bootstrap-3.3.4-dist/css/bootstrap.min.css"%}" rel="stylesheet" media="screen">
  </head>
  <body>
    <div> 
	    {% block content %}
      {% endblock %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function(){
        {% block jquery %}
        {% endblock %}
	    });
    </script>
  </body>
</html>

dropdown/templates/dropdown.html
{% extends "base.html" %}

{% block jquery %}

$("#id_country").change(function(){
  console.log('works');
  $.ajax({

    url : "{% url 'state_ajax' %}",
    type : "POST",
    data : {
      csrfmiddlewaretoken : "{{ csrf_token }}",
      country_id : $("#id_country").val(),
      },
      
    dataType : 'json', 

    success : function(data){

      $("#id_state").empty();      
      $.each(data.state_dict, function(key, value){
        $("#id_state").append('<option value=" ' +key+' ">'+ value +'</option>');
      });

      $("#id_city").empty();
      $.each(data.city_dict, function(key, value){
        $("#id_city").append('<option value=" '+key+' ">'+ value +'</option>');
      });

    },

    error : function(){
      console.log(arguments);

    },

  });
});

{% endblock %}

{% block comment %}
<form id="dropdownform" method="post" action="">
  <div class="col-md-12">
    <div class="col-md-4">
      <label>Country:</label>
        <select name="c_name" id="c_id" class="country">
          <option selected disabled>Select Country</option>
            {% for c in country %}
              <option value="{{ c.id }}">{{ c }}</option>
            {% endfor %}
        </select>
    </div>
   
    <div class="col-md-4">
      <label>State:</label>
        <select name="s_name" id="s_id" class="state">
          <option selected disabled>Select State</option>
            {% for s in state %}
              <option value="{{ s.id }}">{{ s }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="col-md-4">
      <label>City:</label>
        <select name="ci_name" id="ci_id" class="city">
          <option selected disabled>Select City</option>
            {% for ci in city %}
              <option value="{{ ci.id }}">{{ ci }}</option>
            {% endfor %}
        </select>
    </div>
  </div>
</form>
{% endblock %}






{% block content %}
  <form name="dropdownform" method="post" action="">{% csrf_token %}
    <div class="col-md-12">
      <div class="col-md-4">
        {{ form.country.label }}{{form.country}}
      </div> 
      <div class="col-md-4">
        {{ form.state.label }}{{form.state}}
      </div>  
      <div class="col-md-4">
        {{ form.city.label }}{{form.city}}
      </div>
    </div>
 </form>
{% endblock %}